// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Infrastructure.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260109011655_CategoryEnum")]
    partial class CategoryEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Server.Core.Entities.BaseEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("BaseEntity");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Server.Application.Accounts.Entities.Account", b =>
                {
                    b.HasBaseType("Server.Core.Entities.BaseEntity");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasIndex("UserId");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Server.Application.Transactions.Entities.Transaction", b =>
                {
                    b.HasBaseType("Server.Core.Entities.BaseEntity");

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsExpense")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(65,30)");

                    b.HasIndex("AccountId");

                    b.HasIndex("UserId");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("Server.Application.Users.Entities.User", b =>
                {
                    b.HasBaseType("Server.Core.Entities.BaseEntity");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Server.Application.Accounts.Entities.BankAccount", b =>
                {
                    b.HasBaseType("Server.Application.Accounts.Entities.Account");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(65,30)");

                    b.ToTable("bank_accounts", (string)null);
                });

            modelBuilder.Entity("Server.Application.Accounts.Entities.LoanAccount", b =>
                {
                    b.HasBaseType("Server.Application.Accounts.Entities.Account");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsCompoundInterest")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrincipalBalance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TermMonths")
                        .HasColumnType("int");

                    b.ToTable("loan_accounts", (string)null);
                });

            modelBuilder.Entity("Server.Application.Accounts.Entities.RevolvingCreditAccount", b =>
                {
                    b.HasBaseType("Server.Application.Accounts.Entities.Account");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("credit_accounts", (string)null);
                });

            modelBuilder.Entity("Server.Application.Accounts.Entities.Account", b =>
                {
                    b.HasOne("Server.Core.Entities.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("Server.Application.Accounts.Entities.Account", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Application.Users.Entities.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Application.Transactions.Entities.Transaction", b =>
                {
                    b.HasOne("Server.Application.Accounts.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Server.Core.Entities.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("Server.Application.Transactions.Entities.Transaction", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Application.Users.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Application.Users.Entities.User", b =>
                {
                    b.HasOne("Server.Core.Entities.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("Server.Application.Users.Entities.User", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Application.Accounts.Entities.BankAccount", b =>
                {
                    b.HasOne("Server.Application.Accounts.Entities.Account", null)
                        .WithOne()
                        .HasForeignKey("Server.Application.Accounts.Entities.BankAccount", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Application.Accounts.Entities.LoanAccount", b =>
                {
                    b.HasOne("Server.Application.Accounts.Entities.Account", null)
                        .WithOne()
                        .HasForeignKey("Server.Application.Accounts.Entities.LoanAccount", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Application.Accounts.Entities.RevolvingCreditAccount", b =>
                {
                    b.HasOne("Server.Application.Accounts.Entities.Account", null)
                        .WithOne()
                        .HasForeignKey("Server.Application.Accounts.Entities.RevolvingCreditAccount", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Application.Accounts.Entities.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Server.Application.Users.Entities.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
