// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Infrastructure.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Server.Core.Entities.BaseEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("BaseEntity");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Server.Application.Accounts.Entities.Account", b =>
                {
                    b.HasBaseType("Server.Core.Entities.BaseEntity");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasIndex("UserId");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Server.Application.Users.Entities.User", b =>
                {
                    b.HasBaseType("Server.Core.Entities.BaseEntity");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Server.Application.Accounts.Entities.BankAccount", b =>
                {
                    b.HasBaseType("Server.Application.Accounts.Entities.Account");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(65,30)");

                    b.ToTable("bank_accounts", (string)null);
                });

            modelBuilder.Entity("Server.Application.Accounts.Entities.CreditAccount", b =>
                {
                    b.HasBaseType("Server.Application.Accounts.Entities.Account");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PrincipalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TermMonths")
                        .HasColumnType("int");

                    b.ToTable("credit_accounts", (string)null);
                });

            modelBuilder.Entity("Server.Application.Accounts.Entities.Account", b =>
                {
                    b.HasOne("Server.Core.Entities.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("Server.Application.Accounts.Entities.Account", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Application.Users.Entities.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Application.Users.Entities.User", b =>
                {
                    b.HasOne("Server.Core.Entities.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("Server.Application.Users.Entities.User", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Application.Accounts.Entities.BankAccount", b =>
                {
                    b.HasOne("Server.Application.Accounts.Entities.Account", null)
                        .WithOne()
                        .HasForeignKey("Server.Application.Accounts.Entities.BankAccount", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Application.Accounts.Entities.CreditAccount", b =>
                {
                    b.HasOne("Server.Application.Accounts.Entities.Account", null)
                        .WithOne()
                        .HasForeignKey("Server.Application.Accounts.Entities.CreditAccount", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Application.Users.Entities.User", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
